# Generated by Django 3.2 on 2022-11-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Decription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Title',
            field=models.CharField(max_length=100),
        ),
    ]
