# Generated by Django 3.2 on 2022-11-20 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20221120_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='time',
            new_name='Timestamp',
        ),
        migrations.AddField(
            model_name='todo',
            name='Due_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='Tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
