# Generated by Django 3.2 on 2022-11-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20221120_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Timestamp',
            new_name='created_on',
        ),
    ]
