# Generated by Django 3.2 on 2022-11-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_timestamp_todo_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_on',
            new_name='created',
        ),
    ]
