# Generated by Django 3.2 on 2022-11-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Description',
            field=models.TextField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Tag',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
